
<div class="panel panel-default" >
    <div class="panel-heading">
        <span class="panel-title">Bem vindo ao Sistema de Crédito da Prefeitura municipal de caucaia</span>
    </div>
    <div class="panel-body">
        <div>
            <a href="/siscredito/cidadao/solicitacao" title="Click aqui para participar do Programa NOTA CAUCAIA e ganhar descontos de até 100% no IPTU" class="text-info btn btn-danger">Participar do Programa nota Caucaia</a>
        </div>
        <div class="btn">
        </div>
        <div>
            <a href="#" title="Click aqui para participardo Programa NOTA CAUCAIA" class="text-info btn btn-danger"> Veja o regulamento Aqui</a>
        </div>
    </div>
</div>


