<!DOCTYPE html>
<html>
    <header>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Sistema de Crédito - Nota Caucaia</title>
        <link href="/siscredito/resources/css/padrao.css" rel="stylesheet"/>
        <!--<link href="/siscredito/resources/css/bootstrap-theme.min.css" rel="stylesheet"/>-->
        <link href="/siscredito/resources/css/bootstrap.css" rel="stylesheet"/>
    </header>

    <body>
        <ul class="nav nav-tabs nav-divider">
            <?php if (!isset($_SESSION['usuario'])) { ?>
                <li><a href = "/siscredito"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
                <li><a href="/siscredito/usuario/solicitacao"><span class="glyphicon glyphicon-file"></span> Cadastro</a></li>
                <li><a href="/siscredito/usuario/logar"><span class="glyphicon glyphicon-user"></span> Entrar</a></li>
            <?php } elseif (isset($_SESSION['usuario'])) { ?>
                <li><a href = "/siscredito/nota/lancar"><span class="glyphicon glyphicon-plus-sign"></span> Notas</a></li>
                <li><a href = "/siscredito/relatorio/saldo"><span class="glyphicon glyphicon-book"></span> Saldo </a></li>
                <li ><a href="/siscredito/usuario/logout"><span class="glyphicon glyphicon-off"></span> Sair</a></li>
            <?php } ?>
        </ul>
        <div class="panel panel-default">
            <h1><span class="glyphicon glyphicon-globe"></span> Nota Caucaia</h1>
            <span class="small">Sistema de Crédito</span>
            <div class="container">

                <div class='alerta'>
                    <?php echo $this->view->mensagem; ?>
                </div>
                <?php $this->content(); ?>
            </div>
            <div class="panel-footer navbar-fixed-bottom">
                <span class="glyphicon glyphicon-usd" style="font-weight: bold;">SEFIN Caucaia</span>
            </div>
        </div>

        <div class="modal fade bs-example-modal-lg" id="carregando">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h3 class="modal-title"><span id="men_modal"> </span> Aguarde</h3>
                    </div>
                    <div class="modal-body">
                        <div class="progress progress-striped active">
                            <div class="progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                <div id="men_modal"> </div>
                                <span class="sr-only"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="erro">

        </div>
        <script src="/siscredito/resources/js/jquery-1.10.2.min.js" type="text/javascript" ></script>
        <script src="/siscredito/resources/js/bootstrap.min.js" type="text/javascript" ></script>
        <script src="/siscredito/resources/js/jquery.maskMoney.js" type="text/javascript" ></script>
        <script src="/siscredito/resources/js/jquery.mask.min.js" type="text/javascript" ></script>
        <script src="/siscredito/resources/js/functions.js" type="text/javascript" ></script>
    </body>
</html>